---
- hosts: jenkins

  tasks:
   - name: Copy scripts
     copy: src=./devops.py dest=/home/devops/devops.py owner=devops group=devops mode=755

   - name: Get available disk space
     command: ./devops.py
     register: space

   - debug: var=space.stdout_lines
     
