---

#This Playbook installs Docker

- hosts: jenkins
  become: yes
  become_user: root

  vars:
      user: devops

  tasks:
   - name: Check Ubuntu version
     shell: 'cat /etc/lsb-release | grep DISTRIB_RELEASE= | cut -d \= -f 2'
     register: ubuntu_ver

   - debug: var=ubuntu_ver.stdout

   - assert:
       that:
          - "ubuntu_ver.stdout >= '16.04'"
       msg: "Must be Ubuntu 16.04 or later"

   - name: System update and upgrade
     apt:
        upgrade: dist
        update_cache: yes

   - name: Install docker
     apt:
        name: docker.io
        state: latest
     notify:
      - Start docker

   - name: Correct file permission to allow user {{ user }} to run docker
     file:
        path: /var/run/docker.sock
        owner: "{{ user }}"
        group: "{{ user }}"

   - name: Enable docker at system boot
     command: 'systemctl enable docker'

   - name: Check docker version
     command: 'docker version'
     register: docker_ver

   - debug: var=docker_ver.stdout_lines

  handlers:
   - name: Start docker
     service: name=docker state=started