---

#This Playbook downloads and installs Jenkins and Java.

- include: java.yml

- name: Install and run Jenkins
  hosts: jenkins

  vars:
      jenkins_url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
      user: devops
      group: devops
      java_home: /home/{{ user }}/jdk1.8.0_112

  become: yes
  become_user: "{{ user }}"

  gather_facts: False

  tasks:
    - name: Kill any running Jenkins process if any
      script: ./devops.py kill_process\('jenkins.sh'\)

    - name: Download Jenkins
      get_url:
          url: "{{ jenkins_url }}"
          dest: "/home/{{ user }}/jenkins.war"
          mode: 0440

    - name: Create Jenkins startup shell script, jenkins.sh
      copy:
          content: "{{ java_home }}/bin/java -jar /home/{{ user }}/jenkins.war"
          dest: "/home/{{ user }}/jenkins.sh"
          mode: 0744

    - name: Start Jenkins
      shell: 'nohup /home/{{ user }}/jenkins.sh > /dev/null 2>&1 &'