---

#This Playbook downloads and installs Jenkins and Java.

- hosts: jenkins

  vars:
      jenkins_url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
  gather_facts: False

  tasks:
   - name: Install Unzip
     apt: name=unzip state=installed

   - name: Create jenkins directory
     file: path=~/jenkins state=directory owner=devops group=devops mode=0775

   - name: Download Jenkins
     get_url:
        url: "{{ jenkins_url }}"
        dest: ~/jenkins.war
        mode: 0440

   - name: Unzip Jenkins war file
     unarchive:
         src: ~/jenkins.war
         dest: ~/jenkins
         remote_src: True

   - name: Remove the Jenkins downloaded package
     file: state=absent path=~/jenkins.war