---

#This Playbook downloads and installs Jenkins and Java.

- hosts: jenkins
  become: yes
  become_user: root

  vars:
      jenkins_url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
  gather_facts: False

  tasks:
   - name: Install Unzip
     apt: name=unzip state=installed

   - name: Create jenkins directory
     file: path=~/jenkins state=directory owner=devops group=devops mode=0775

   - name: Download and unzip Jenkins war file
     unarchive:
         src: "{{jenkins_url}}"
         copy: no
         dest: ~/jenkins